### ISSUE TITLE
Language toggling not working properly.

### ISSUE THREAD

**Issue by usithadev** [wppconnect-team/wppconnect-team.github.io#105]
I tried to toggle the language on the website from Portuguese to English, but the language remained in Portuguese. I tried this several times and even cleared my browser cache, but the issue persists. Please fix this bug so that users can properly use the language toggling menu.

**Comment by edgardmessias** [comment]
Sorry @usithadev , but I am translating the content, there a lot of content in Portuguese, this is not a bug

**Comment by usithadev** [comment]
Thank you for the clarification, @edgardmessias. I understand the situation and will close the issue.
